"""add image in Employee table

Revision ID: 26c7cc10a302
Revises: 72a5a240aec9
Create Date: 2023-05-28 00:57:02.611714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c7cc10a302'
down_revision = '72a5a240aec9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'image_path')
    # ### end Alembic commands ###
