"""add follower table

Revision ID: 626f9f9ec411
Revises: d3ef7ec792f4
Create Date: 2023-05-26 23:33:23.861741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626f9f9ec411'
down_revision = 'd3ef7ec792f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
