"""add userImage table

Revision ID: 72a5a240aec9
Revises: 626f9f9ec411
Create Date: 2023-05-27 15:49:09.382972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a5a240aec9'
down_revision = '626f9f9ec411'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userImages', sa.Column('created_at', sa.Date(), nullable=False))
    op.add_column('userImages', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'userImages', ['user_id'])
    op.create_foreign_key(None, 'userImages', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userImages', type_='foreignkey')
    op.drop_constraint(None, 'userImages', type_='unique')
    op.drop_column('userImages', 'user_id')
    op.drop_column('userImages', 'created_at')
    # ### end Alembic commands ###
