"""update tables

Revision ID: 8928ccd870f9
Revises: e16344c67762
Create Date: 2023-06-06 23:55:10.237788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8928ccd870f9'
down_revision = 'e16344c67762'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('experience', sa.String(), nullable=False))
    op.drop_column('experience', 'end_date')
    op.drop_column('experience', 'company')
    op.drop_column('experience', 'role')
    op.drop_column('experience', 'description')
    op.drop_column('experience', 'start_date')
    op.drop_column('organization', 'name')
    op.drop_column('patients', 'name')
    op.drop_column('professionals', 'name')
    op.add_column('qualification', sa.Column('qualification', sa.String(), nullable=False))
    op.drop_column('qualification', 'completion_date')
    op.drop_column('qualification', 'degree')
    op.drop_column('qualification', 'grade')
    op.drop_column('qualification', 'college')
    op.drop_column('qualification', 'start_date')
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.add_column('qualification', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('qualification', sa.Column('college', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('qualification', sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('qualification', sa.Column('degree', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('qualification', sa.Column('completion_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('qualification', 'qualification')
    op.add_column('professionals', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('organization', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('experience', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('experience', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('experience', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('experience', sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('experience', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('experience', 'experience')
    # ### end Alembic commands ###
