"""add new columns to qualificatio and experience

Revision ID: c5b5cdf51899
Revises: 
Create Date: 2023-07-10 17:09:45.845466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b5cdf51899'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('company', sa.String(), nullable=False))
    op.add_column('experience', sa.Column('role', sa.String(), nullable=False))
    op.add_column('experience', sa.Column('description', sa.String(), nullable=False))
    op.add_column('experience', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('experience', sa.Column('end_date', sa.Date(), nullable=False))
    op.add_column('qualification', sa.Column('degree', sa.String(), nullable=False))
    op.add_column('qualification', sa.Column('college', sa.String(), nullable=False))
    op.add_column('qualification', sa.Column('grade', sa.String(), nullable=False))
    op.add_column('qualification', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('qualification', sa.Column('completion_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qualification', 'completion_date')
    op.drop_column('qualification', 'start_date')
    op.drop_column('qualification', 'grade')
    op.drop_column('qualification', 'college')
    op.drop_column('qualification', 'degree')
    op.drop_column('experience', 'end_date')
    op.drop_column('experience', 'start_date')
    op.drop_column('experience', 'description')
    op.drop_column('experience', 'role')
    op.drop_column('experience', 'company')
    # ### end Alembic commands ###
