"""set relation between appllication and professionals

Revision ID: d3ef7ec792f4
Revises: db74b708ae85
Create Date: 2023-05-26 15:22:06.775654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ef7ec792f4'
down_revision = 'db74b708ae85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('professional_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'applications', 'professionals', ['professional_id'], ['professional_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'professional_id')
    # ### end Alembic commands ###
