"""Initial migration

Revision ID: db74b708ae85
Revises: e02a77944df1
Create Date: 2023-05-26 00:42:46.261321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db74b708ae85'
down_revision = 'e02a77944df1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
