"""Set Date in Posts Table

Revision ID: e02a77944df1
Revises: 61873bd485d1
Create Date: 2023-05-26 00:39:43.722322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e02a77944df1'
down_revision = '61873bd485d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
