"""add timming field in employee table

Revision ID: e16344c67762
Revises: 26c7cc10a302
Create Date: 2023-05-29 20:12:14.270745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e16344c67762'
down_revision = '26c7cc10a302'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('timming', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'timming')
    # ### end Alembic commands ###
